; This file was auto-generated by drush make
api = 2
core = 7.x

;Installing AWS SDK
projects[awssdk][type] = library
projects[awssdk][download][type] = git
projects[awssdk][download][url] = https://github.com/amazonwebservices/aws-sdk-for-php.git
projects[awssdk][download][tag] = 1.5.10
projects[libraries] = 2

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.0"

projects[admin_path][subdir] = "contrib"
projects[admin_path][version] = "1.0"

projects[advanced_help][subdir] = "contrib"
projects[advanced_help][version] = "1.0"

projects[auto_entitylabel][subdir] = "contrib"
projects[auto_entitylabel][version] = "1.1"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "2.4"

projects[browscap][subdir] = "contrib"
projects[browscap][version] = "1.3"

projects[browscap_ctools][subdir] = "contrib"
projects[browscap_ctools][version] = "1.0"

projects[bulk_media_upload][subdir] = "contrib"
projects[bulk_media_upload][version] = "1.x-dev"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.2"

projects[ccl][subdir] = "contrib"
projects[ccl][version] = "1.x-dev"

projects[colorbox][subdir] = "contrib"
projects[colorbox][version] = "1.3"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.3"

projects[diff][subdir] = "contrib"
projects[diff][version] = "2.0"

projects[draggableviews][subdir] = "contrib"
projects[draggableviews][version] = "2.0"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.0-rc3"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.x-dev"

projects[entityreference_prepopulate][subdir] = "contrib"
projects[entityreference_prepopulate][version] = "1.1"

projects[entityreference_view_widget][subdir] = "contrib"
projects[entityreference_view_widget][version] = "1.0-alpha2"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "1.0"

projects[link][subdir] = "contrib"
projects[link][version] = "1.0"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.7"

projects[openfolio_features][subdir] = "contrib"
projects[openfolio_features][download][type] = "git"
projects[openfolio_features][download][branch] = "7.x-1.x"
projects[openfolio_features][subdir] = "contrib"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.3"

projects[panopoly_theme][subdir] = "contrib"
projects[panopoly_theme][version] = "1.0-beta6"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[plupload][subdir] = "contrib"
projects[plupload][version] = "1.0"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.2"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.4"

projects[views][subdir] = "contrib"
projects[views][version] = "3.5"

projects[views_slideshow][subdir] = "contrib"
projects[views_slideshow][version] = "3.0"

projects[uuid][subdir] = "contrib"
projects[uuid][download][type] = git
projects[uuid][download][revision] = 4730c678a5a09ab0529ea3222e6123bd929b8da0
projects[uuid][download][branch] = 7.x-1.x

projects[node_export][subdir] = "contrib"
projects[node_export][version] = "3.0"


; Themes
projects[adaptivetheme][version] = "2.3"
projects[corolla][version] = "2.2"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "http://jacklmoore.com/colorbox/colorbox.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = "get"
libraries[jquery.cycle][download][url] = "http://malsup.github.com/jquery.cycle.all.js"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[json2][download][type] = "get"
libraries[json2][download][url] = "https://github.com/douglascrockford/JSON-js/zipball/master"
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[plupload][download][type] = "get"
libraries[plupload][download][url] = "https://github.com/downloads/moxiecode/plupload/plupload_1_5_4.zip"
libraries[plupload][directory_name] = "plupload"
libraries[plupload][type] = "library"

